name: CI/CD Pipeline for Docker Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow only for pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

       # Step #: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t sahal6282/docker:latest .

      # Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push sahal6282/docker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job has been completed before deployment

    steps:
      # Checkout the code again to access your SSH configuration
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH for EC2 deployment
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Deploy Docker container to EC2
      - name: Deploy Docker image to EC2
        run: |
          # Add the EC2 private key to the SSH agent
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 5000:5000 sahal6282/docker:latest
          EOF
