name: CI/CD Pipeline #

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Test the application
      run: python -m unittest discover

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy and Restart Application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/Task/flasktask || { echo "Directory not found"; exit 1; }
          docker build -t flask-app .
          docker stop flask-app-container || true
          docker rm flask-app-container || true
          docker run -d -p 80:5000 --name flask-app-container flask-app
        EOF
